# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
default_q: [
    0.0,-0.6,0.3,0.0,0.0,0.0
]

acceleration_limits: [
   10,10,10,10,10,10
]

jerk_limits: [
   100,100,100,100,100,100
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:
    - {name: left_joint, rule: fixed, value: 0.0366}
    - {name: right_joint, rule: fixed, value: 0.0366}

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  - link1:
    - "center": [0.0, 0.0, -0.004]
      "radius": 0.05
  - link2:
    - "center": [0.001, 0.002, 0.0]
      "radius": 0.07
    - "center": [0.267, 0.005, -0.0]
      "radius": 0.05
    - "center": [0.047, 0.012, -0.0]
      "radius": 0.06544
    - "center": [0.107, 0.011, -0.0]
      "radius": 0.06119
    - "center": [0.152, 0.016, -0.0]
      "radius": 0.0572
    - "center": [0.204, 0.015, -0.0]
      "radius": 0.05348
  - link3:
    - "center": [0.004, 0.004, 0.0]
      "radius": 0.06
    - "center": [-0.001, 0.228, -0.0]
      "radius": 0.04
    - "center": [0.003, 0.056, 0.0]
      "radius": 0.05533
    - "center": [0.002, 0.105, -0.0]
      "radius": 0.05102
    - "center": [0.001, 0.149, -0.0]
      "radius": 0.04704
    - "center": [0.0, 0.19, -0.0]
      "radius": 0.04338
  - link4:
    - "center": [-0.0, 0.001, -0.007]
      "radius": 0.04
  - link5:
    - "center": [-0.0, 0.034, -0.004]
      "radius": 0.06
  - link6:
    - "center": [-0.0, -0.005, 0.117]
      "radius": 0.04
    - "center": [-0.056, -0.009, 0.161]
      "radius": 0.02
    - "center": [0.057, -0.01, 0.16]
      "radius": 0.02
    - "center": [-0.034, -0.009, 0.161]
      "radius": 0.02
    - "center": [-0.011, -0.009, 0.161]
      "radius": 0.02
    - "center": [0.012, -0.009, 0.16]
      "radius": 0.02
    - "center": [0.035, -0.01, 0.16]
      "radius": 0.02
    - "center": [-0.058, 0.016, 0.159]
      "radius": 0.02
    - "center": [0.056, 0.015, 0.159]
      "radius": 0.02
    - "center": [-0.035, 0.016, 0.159]
      "radius": 0.02
    - "center": [-0.012, 0.016, 0.159]
      "radius": 0.02
    - "center": [0.01, 0.015, 0.159]
      "radius": 0.02
    - "center": [0.033, 0.015, 0.159]
      "radius": 0.02
  - left_link:
    - "center": [0.076, 0.001, -0.0]
      "radius": 0.01
    - "center": [0.054, 0.0, 0.007]
      "radius": 0.02
    - "center": [0.023, 0.015, 0.012]
      "radius": 0.02
    - "center": [0.028, -0.018, 0.009]
      "radius": 0.02
    - "center": [0.014, -0.017, 0.015]
      "radius": 0.02
  - right_link:
    - "center": [0.016, -0.017, 0.013]
      "radius": 0.02
    - "center": [0.017, 0.016, 0.014]
      "radius": 0.02
    - "center": [0.036, -0.007, 0.009]
      "radius": 0.02
    - "center": [0.046, 0.011, 0.01]
      "radius": 0.02
    - "center": [0.077, 0.002, 0.002]
      "radius": 0.01
    - "center": [0.064, -0.002, 0.0]
      "radius": 0.015
